--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ruther/.config/wallpaper.png"

-- Special
background="#0F1624"
foreground="#c5c6e7"
cursor="#c5c6e7"

-- Colors
color0="#0F1624"
color1="#0c1dee"
color2="#0c21ec"
color3="#4051f4"
color4="#e118f2"
color5="#4897f5"
color6="#21d1f3"
color7="#c5c6e7"
color8="#898aa1"
color9="#0c1dee"
color10="#0c21ec"
color11="#4051f4"
color12="#e118f2"
color13="#4897f5"
color14="#21d1f3"
color15="#c5c6e7"
