# Shell variables
# Generated by 'wal'
wallpaper="/home/ruther/.config/wallpaper.png"

# Special
background='#0F1624'
foreground='#c5c6e7'
cursor='#c5c6e7'

# Colors
color0='#0F1624'
color1='#0c1dee'
color2='#0c21ec'
color3='#4051f4'
color4='#e118f2'
color5='#4897f5'
color6='#21d1f3'
color7='#c5c6e7'
color8='#898aa1'
color9='#0c1dee'
color10='#0c21ec'
color11='#4051f4'
color12='#e118f2'
color13='#4897f5'
color14='#21d1f3'
color15='#c5c6e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
