# Shell variables
# Generated by 'wal'
wallpaper="/home/ruther/.config/wallpaper.png"

# Special
background='rgba(15,22,36,0.8)'
foreground='rgba(197,198,231,0.8)'
cursor='rgba(197,198,231,0.8)'

# Colors
color0='rgba(15,22,36,0.8)'
color1='rgba(12,29,238,0.8)'
color2='rgba(12,33,236,0.8)'
color3='rgba(64,81,244,0.8)'
color4='rgba(225,24,242,0.8)'
color5='rgba(72,151,245,0.8)'
color6='rgba(33,209,243,0.8)'
color7='rgba(197,198,231,0.8)'
color8='rgba(137,138,161,0.8)'
color9='rgba(12,29,238,0.8)'
color10='rgba(12,33,236,0.8)'
color11='rgba(64,81,244,0.8)'
color12='rgba(225,24,242,0.8)'
color13='rgba(72,151,245,0.8)'
color14='rgba(33,209,243,0.8)'
color15='rgba(197,198,231,0.8)'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
