#!/bin/sh

#PROMPT_COMMAND=__prompt_command    # Function to generate PS1 after CMDs
#__prompt_command() {
#    local EXIT="$?"                # This needs to be first
#    PS1=""
#
#    local RCol='\[\e[0m\]'
#
#    local Red='\[\e[0;31m\]'
#    local Gre='\[\e[0;32m\]'
#    local BYel='\[\e[1;33m\]'
#    local BBlu='\[\e[1;34m\]'
#    local Pur='\[\e[0;35m\]'
#
#    if [ $EXIT != 0 ]; then
#        PS1+="[${Red}\u${RCol}"        # Add red if exit code non 0
#    else
#        PS1+="[${Gre}\u${RCol}"
#    fi
#
#    PS1+="${RCol}@${BBlu}\h ${Pur}\w${BYel}${RCol}]$ "
#}

# My name
#------------------
branch() {
    b="$(git branch 2>/dev/null)"
    if [ -z "$b" ]; then
        printf ""
    else
        printf "($(git branch 2>/dev/null | grep '^*' | colrm 1 2))"
    fi
}

python-venv() {
    venv="$(basename ${VIRTUAL_ENV} 2> /dev/null)"
    if [ -z "$venv" ]; then
        printf ""
    else
        printf "($venv)"
    fi
}

PROMPT_COMMAND=__prompt_command
__prompt_command() {
    PS1="•$(python-venv)$(yellow '[')$(blue '\u')@$(red '\h') $(green '\w')$(yellow ']$(branch)$ ')
$(blinking-green '└-----------$(($(ls -la ~ | wc -l)-3))---->') "
}
