# Shell variables
# Generated by 'wal'
wallpaper="{wallpaper}"

# Special
background='{background.rgba}'
foreground='{foreground.rgba}'
cursor='{cursor.rgba}'

# Colors
color0='{color0.rgba}'
color1='{color1.rgba}'
color2='{color2.rgba}'
color3='{color3.rgba}'
color4='{color4.rgba}'
color5='{color5.rgba}'
color6='{color6.rgba}'
color7='{color7.rgba}'
color8='{color8.rgba}'
color9='{color9.rgba}'
color10='{color10.rgba}'
color11='{color11.rgba}'
color12='{color12.rgba}'
color13='{color13.rgba}'
color14='{color14.rgba}'
color15='{color15.rgba}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"
