#!/bin/sh

# Get the data from the rss feed.
data=$(curl https://www.erai-raws.info/rss-1080 | grep -A2 "$1")

# If there is no data, close the script.
[ -z $data ] && exit 0

# Get the link.
link=$(echo "$data" | grep link | sed -r 's,.*<link>(.*)</link>.*,\1,')

# Download it to a temp file.
wget $link -O "~/downs/$1.torrent"
