#!/bin/sh

charge=$(cat /sys/class/power_supply/BAT*/capacity || echo "")
plugged=$(cat /sys/class/power_supply/AC/online || echo "")

[ $plugged -eq 1 ] &&
printf "AC: %s $(acpi | cut -d',' -f3 | cut -d' ' -f2)" "%$charge" ||
printf "BAT: %s $(acpi | cut -d',' -f3 | cut -d' ' -f2)" "%$charge"
