#!/bin/bash

tiempo=$1
n=0
device_id=12

xinput set-prop $device_id 'Device Enabled' 0

while [ $n -lt $tiempo ]
do
    echo Reactivando teclado en $(($tiempo-$n)) segundos..
    sleep 1s
    ((n=$n+1))
done
xinput set-prop $device_id 'Device Enabled' 1
