#!/bin/sh
#ffmpeg -i $1 -vcodec libvpx-vp9 -crf 20 $2.mp4

if [ -z $2 ]; then

    ffmpeg -i "$1" -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p "${1%.*}-compressed.mp4"
else
    ffmpeg -i "$1" -ss $2 -to $3 -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p "${1%.*}-cut.mp4"
fi
