#!/bin/sh

mounted=$(lsblk -l | awk '{print $7}' | sed '/^$/d' | tail -n +2)
space=" "
for drive in $mounted
do	
	[ $drive != "/boot" ] &&
		printf "[/${drive##*/}" &&
		printf " $(free_space "available" $drive)]"
done
