#!/bin/sh

case "$1" in
    office)
        autorandr left_mon
        $VISUAL ${XDG_DOCUMENTS_DIR}/vimwiki/index.wiki
    ;;
    fenvelopes)
        fenvdir="${XDG_DOCUMENTS_DIR}/research/thermo/algos/envelopes"
        cd "$fenvdir"
        shopt -s expand_aliases
        source "$fenvdir/paper/fcmmp/input_files/runner.sh"
        bash
    ;;
esac
