#!/bin/sh

file="$HOME/pics/screens/scr--$(date '+%Y-%m-%d--%H:%M:%S').png"

# adding -silent argument would stop the audio from the PC speaker,
# I find it funny tho

case $@ in
	"-fs")
		import -silent -window root "$file"
		xclip -i -t image/png -sel clip < "$file";;
	"-s")
		import -silent "$file"
		xclip -i -t image/png -sel clip < "$file";;
	"-sw")
		file="/tmp/scr--$(date '+%Y-%m-%d--%H:%M:%S').png"
		import -silent "$file"
		sxiv "$file"
esac
