#!/bin/sh

file="$HOME/pics/screens/scr--$(date '+%Y-%m-%d--%H:%M:%S').png"

# adding -silent argument would stop the audio from the PC speaker,
# I find it funny tho

case $@ in
	"-fs")
		import -silent -window root "$file"
		xclip -i -t image/png -sel clip < "$file";;
	"-s")
		import -silent "$file"
		xclip -i -t image/png -sel clip < "$file";;
	"-sw")
		file="/tmp/scr--$(date '+%Y-%m-%d--%H:%M:%S').png"
		import -silent "$file"
		sxiv "$file";;
	"-tex")
		mkdir "./figs" 2> /dev/null
		file="$(pwd)/figs/scr--$(date '+%Y-%m-%d--%H:%M:%S').png"
		import -silent "$file"
		echo -n "
	\begin{center}
	\begin{figure}[h]
		\includegraphics[width=0.7\textwidth]{$file}
	\end{figure}
	\end{center}" ;;
	"-qr")
		echo "qr"
		file="/tmp/scr--$(date '+%Y-%m-%d--%H:%M:%S').png"
		import -silent "$file"
		zbarimg "$file"
		;;
esac
