#!/bin/sh
SINK_FILE="${XDG_HOME_DIR:-$HOME}.cache/sink"

choose() {
    sinks="$(pactl list sinks | egrep "(Name)|(Description)")"
    sink="$(echo "$sinks" | grep "Description" | dmenu -l 5)"
    sink_name=$(echo "$sinks" | grep -P1 "$sink" | head -n1 | cut -d' ' -f2)
    echo selected "$sink_name"

    echo echo $sink_name > "${SINK_FILE}"
    echo $sink_name > "${SINK_FILE}"
}


set_default() {
    pactl set-default-sink $(cat "$SINK_FILE")
}


find_id(){
    sinkID=$(wpctl status |
        grep "$1" |
        awk '{print $3}'
    )
    sinkID=${sinkID%.*}
}


dirty_default() {
    sinkID=52
    sourceID=48
    wpctl set-default $sinkID
    wpctl set-default $sourceID
}


case $1 in
    "choose")
        choose
        set_default;;

    "set")
        set_default;;
    *)
        dirty_default;;
esac
