#!/bin/sh

CONFIG_DIR="${XDG_CONFIG_DIR:-$HOME/.config}/dunst"
DUNST_RC="$CONFIG_DIR/dunstrc"

# Get the data from the pywal cache folder.
. ${XDG_CACHE_DIR:-$HOME/.cache}/wal/colors.sh
# If a folder is given, read the data from there
[ -z "$1"  ] || . "$1"/colors.sh

conf="$(cat <<LIM
background = "$background"
foreground = "$foreground"
frame_color = "$color2"
LIM
)"

IFS=$'\n'
for setting in $(echo "$conf"); do
	sett=$(echo "$setting" | cut -d' ' -f1)
	sed -i "s/$sett.*/$setting/g" $DUNST_RC
done

killall dunst && notify-send "Dunst reloaded"
