#!/bin/sh

CONFIG_DIR="${XDG_CONFIG_DIR:-$HOME/.config}/zathura"
ZATH_RC="$CONFIG_DIR/zathurarc"

. ${XDG_CACHE_DIR:-$HOME/.cache}/wal/zathura.sh
[ -z "$1" ] || . "$1"/zathura.sh
cp "$ZATH_RC" "$CONFIG_DIR/zathurarc.b"

conf="$(cat <<LIM
set recolor "true"
set completion-bg "$background"
set completion-fg "$foreground"
set completion-group-bg "$background"
set completion-group-fg "$color2"
set completion-highlight-bg "$foreground"
set completion-highlight-fg "$background"
set recolor-lightcolor "$background"
set recolor-darkcolor "$foreground"
set default-bg "$background"
set inputbar-bg "$background"
set inputbar-fg "$foreground"
set notification-bg "$background"
set notification-fg "$foreground"
set notification-error-bg "$color1"
set notification-error-fg "$foreground"
set notification-warning-bg "$color1"
set notification-warning-fg "$foreground"
set statusbar-bg "$background"
set statusbar-fg "$foreground"
set index-bg "$background"
set index-fg "$foreground"
set index-active-bg "$foreground"
set index-active-fg "$background"
set render-loading-bg "$background"
set render-loading-fg "$foreground"
set window-title-home-tilde true
set statusbar-basename true
set selection-clipboard clipboard
LIM
)"

cases=$(echo "$conf" | cut -d' ' -f1-2)
IFS=$'\n'

i=0
for case in $cases; do
	sed -i "/$case/d" "$ZATH_RC"
done

echo "$conf" >> "$ZATH_RC"
