#!/bin/sh

echo Loading default Xresources
xrdb "$XRESOURCES"
echo Merging pywal Xresources
[ -f "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.Xresources" ] && xrdb -merge ${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.Xresources &
[ -f "${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors-wal-dwm.h" ] && dwm_colors & # xrdb -merge ${XDG_CACHE_HOME:-$HOME/.cache}/dwm_bar_colors &

