--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1c2319"
foreground="#be9e61"
cursor="#bcbebb"

-- Colors
color0="#1c2319"
color1="#c14d38"
color2="#a0ce52"
color3="#be9e61"
color4="#4c7e89"
color5="#814d61"
color6="#79a69d"
color7="#bcbebb"
color8="#35422f"
color9="#c14d38"
color10="#a0ce52"
color11="#be9e61"
color12="#4c7e89"
color13="#814d61"
color14="#79a69d"
color15="#bcbebb"
