# Shell variables
# Generated by 'wal'
wallpaper="None"

# Special
background='rgba(28,35,25,1.0)'
foreground='rgba(190,158,97,1.0)'
cursor='rgba(188,190,187,1.0)'

# Colors
color0='rgba(28,35,25,1.0)'
color1='rgba(193,77,56,1.0)'
color2='rgba(160,206,82,1.0)'
color3='rgba(190,158,97,1.0)'
color4='rgba(76,126,137,1.0)'
color5='rgba(129,77,97,1.0)'
color6='rgba(121,166,157,1.0)'
color7='rgba(188,190,187,1.0)'
color8='rgba(53,66,47,1.0)'
color9='rgba(193,77,56,1.0)'
color10='rgba(160,206,82,1.0)'
color11='rgba(190,158,97,1.0)'
color12='rgba(76,126,137,1.0)'
color13='rgba(129,77,97,1.0)'
color14='rgba(121,166,157,1.0)'
color15='rgba(188,190,187,1.0)'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
